import Head from "next/head";
import { FcGoogle } from "react-icons/fc";
import { FaFacebookSquare, FaLinkedin } from "react-icons/fa";
import { BsEnvelope } from "react-icons/bs";
import { GiPadlock } from "react-icons/gi";

export default function Login() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen py2 bg-gray-200 sc:invisible  ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <div className="sc: visible font-bold text-2xl sc:bg-gray-200 w-screen h-screen flex flex-col justify-center lg:invisible lg:h-0">
          <h1 className="text-gray-400">
            Meireles e Freitas <span className=" text-green-500">Digital</span>
          </h1>
          <h2 className="text-gray-400 mt-5">
            Para sua melhor experiência, utilize dispositivos desktops!
          </h2>
        </div>
        <div className="bg-white rounded-2xl shadow-2xl flex w-2/3 max-w-4xl">
          <div className="w-3/5 p-5">
            <div className="text-left font-bold">
              Meireles e Freitas <span className="text-green-500">Digital</span>
            </div>
            <div className="py-10 ">
              <h2 className="text-3xl font-bold text-green-500 mb-2">
                Workspace
              </h2>
              <div className="border-2 w-10 border-green-500 inline-block mb-2"></div>
              <div className="flex justify-center my-2">
                <a
                  href="#"
                  className=" border-2 border-gray-200 rounded-full p-3 mx-1"
                >
                  <FcGoogle />
                </a>
                <a
                  href="#"
                  className=" border-2 border-gray-200 rounded-full p-3 mx-1 text-blue-700"
                >
                  <FaFacebookSquare />
                </a>
                <a
                  href="#"
                  className=" border-2 border-gray-200 rounded-full p-3 mx-1 text-blue-700"
                >
                  <FaLinkedin />
                </a>
              </div>
              <p className="text-gray-400 m-2">
                Acesse também com e-mail/password cadastrado!
              </p>
              <div className="flex flex-col items-center ">
                <div className="bg-gray-100 w-64 p-2 flex items-center rounded-full mb-3">
                  <BsEnvelope className="text-gray-400 mr-2" />
                  <input
                    type="email"
                    name="email"
                    placeholder="email@exemplo.com"
                    className="bg-gray-100 outline-none text-md w-64 flex-1"
                  />
                </div>
                <div className="bg-gray-100 w-64 p-2 flex items-center rounded-full">
                  <GiPadlock className="text-gray-400 mr-2" />
                  <input
                    type="password"
                    name="password"
                    placeholder="password"
                    className="bg-gray-100 outline-none text-md w-64 flex-1 "
                  />
                </div>
                <div className="flex w-64 mb-5 justify-center">
                  <a
                    href="#"
                    className="text-xs mt-2 text-green-600  hover:text-slate-700"
                  >
                    Esqueceu a senha?
                  </a>
                </div>
                <a
                  href="#"
                  className="border-2 border-green-500 rounded-full text-green-500 px-12 py-2 inline-block font-semibold hover:bg-green-500 hover:text-white"
                >
                  Entrar
                </a>
              </div>
            </div>
          </div>
          <div className="w-3/5 bg-green-400 text-white rounded-tr-2xl rounded-br-2xl py-36 px-12 lg:flex lg:flex-col lg:text-center">
            <h2 className="text-3xl font-bold mb-2">Olá, Colaborador(a)!</h2>
            <div className="border-2 w-10 border-white inline-block mb-2 "></div>
            <p className="mb-10">
              Antes de iniciar o cadastro na plataforma, consulte seu gestor
              imediato!
            </p>
            <a
              href="#"
              className="border-2  border-white rounded-full px-12 py-2  font-semibold hover:bg-white hover:text-green-500  "
            >
              Registrar
            </a>
          </div>
        </div>
      </main>
    </div>
  );
}
